a=input('Enter the first no:\n')
b=input('Enter the second no:\n')
a=int(a)
b=int(b)
add=(a+b)
print('Addition:',add)
sub=(a-b)
print('Subraction:',sub)
mul=(a*b)
print('Multipication:',mul)
div=(a/b)
print('Division:',div)
